import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    signIn: "Sign In",
    getStarted: "Get Started",
    aiPowered: "AI-Powered Farm Intelligence",
    growSmarter: "Grow smarter.",
    sellBetter: "Sell better.",
    earnMore: "Earn more.",
    heroSubtitle: "AgriRakshak combines weather forecasting, real-time mandi prices, and machine learning.",
    startFree: "Start for free",
    farmerLogin: "Farmer login",
    ticker: ["Weather Forecast", "Mandi Prices", "ML Harvest", "Transport", "AI Insights", "Alerts", "Compare", "Reports"],
    recommendationsServed: "Recommendations",
    mandiPriceRecords: "Price Records",
    cropsSupported: "Crops",
    farmersOnboarded: "Farmers",
    coreTechnology: "Core Technology",
    everythingFarming: "Everything for smart farming",
    featuresSubtitle: "Four pillars of intelligence working together.",
    weatherIntelligence: "Weather Intelligence",
    weatherDesc: "Real-time weather analysis predicts spoilage risk.",
    mandiPrediction: "Price Prediction",
    mandiDesc: "ML models forecast prices 7 days ahead.",
    transportCost: "Transport Cost",
    transportDesc: "Factor in fuel, distance, and logistics.",
    aiDecisions: "AI Decisions",
    aiDesc: "Every recommendation comes with explanation.",
    simpleProcess: "Simple Process",
    threeSteps: "Three steps to profit",
    howSubtitle: "From sign-up to recommendation in minutes.",
    connectFarm: "Connect Your Farm",
    connectFarmDesc: "Enter your location and crops.",
    aiRec: "Get Recommendations",
    aiRecDesc: "Models analyze weather and prices.",
    sellRight: "Sell at Right Price",
    sellRightDesc: "Choose optimal window and maximize profit.",
    joinBeta: "Join Beta",
    ctaTitle: "Ready to earn more?",
    ctaSubtitle: "Join farmers using data-driven decisions.",
    helpFeedback: "Help & Feedback",
    shareThoughts: "Share your thoughts",
    feedbackSubtitle: "Help us build the best tool.",
    yourName: "Your name",
    emailOptional: "Email (optional)",
    selectType: "Select type",
    featureSuggestion: "Feature suggestion",
    bugReport: "Report a bug",
    missingMandi: "Missing mandi/crop",
    generalFeedback: "General feedback",
    tellUs: "Tell us what you think...",
    sendFeedback: "Send Feedback",
    thankYouFeedback: "Thank you! Feedback received.",
    govtPortals: "Government Portals",
    downloadApp: "Download App",
    getPlayStore: "Get on Google Play",
    getAppStore: "Download on App Store",
    product: "Product",
    features: "Features",
    howItWorks: "How It Works",
    supportedCrops: "Supported Crops",
    pricing: "Pricing",
    changelog: "Changelog",
    resources: "Resources",
    documentation: "Documentation",
    apiAccess: "API Access",
    blog: "Blog",
    faqs: "FAQs",
    contactSupport: "Contact Support",
    dashboard: "Dashboard",
    getRecommendation: "Get Recommendation",
    livePrices: "Live Prices",
    weather: "Weather",
    simulator: "Simulator",
    history: "History",
    farmerPortal: "Farmer Portal",
    quickStats: "Quick Stats",
    recommendations: "Recommendations",
    activeCrop: "Active Crop",
    region: "Region",
    notSet: "Not set",
    signOut: "Sign out",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    farmOverview: "Your farm intelligence overview.",
    cropsAvailable: "Crops Available",
    latestEstProfit: "Est. Profit",
    spoilageRisk: "Spoilage Risk",
    getAiRec: "Get AI recommendation",
    recSubtitle: "Select crop, region and quantity.",
    crop: "Crop",
    regionState: "Region (State)",
    quantity: "Quantity (quintals)",
    analyze: "Analyze",
    analyzing: "Analyzing...",
    soilData: "Soil Data (Optional)",
    soilPh: "Soil pH",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    storageConditions: "Storage Conditions",
    storageTemp: "Storage Temp",
    humidity: "Humidity (%)",
    transitTime: "Transit Time",
    aiRecommendation: "AI Recommendation",
    basedOnWeather: "Based on weather and prices",
    harvestWindow: "Harvest Window",
    bestNetReturn: "Best net return",
    priceQuintal: "Price/quintal",
    estNetProfit: "Est. Net Profit",
    aiExplanation: "AI Explanation",
    soilSuitability: "Soil suitability",
    selectCrop: "Select crop",
    pleaseSelectCrop: "Please select a crop.",
    pleaseEnterRegion: "Please enter a region.",
    failedToGenerate: "Failed to generate recommendation.",
    noLivePrices: "No live prices available.",
    enterRegionCrop: "Enter region and select crop.",
    noRecommendations: "No recommendations yet.",
    pastRecommendations: "Past Recommendations",
    cropOptimalRanges: "Optimal Ranges",
    preservationRecommendations: "Preservation Tips",
    cost: "Cost",
    effectiveness: "Effectiveness",
    spoilageRiskEstimator: "Spoilage Risk",
    lowRisk: "Low Risk",
    moderateRisk: "Moderate Risk",
    highRisk: "High Risk",
    // Login/Register
    welcomeBack: "Welcome back",
    loginSubtitle: "Your personalized harvest and market intelligence is waiting. Log in to see today's AI recommendations.",
    feature1: "7-day weather harvest windows",
    feature2: "Live mandi price predictions",
    feature3: "Transport cost optimisation",
    feature4: "Explainable AI insights",
    todaysMarket: "Today's Market Pulse",
    wheat: "Wheat",
    soybean: "Soybean",
    cotton: "Cotton",
    nagpurApmc: "Nagpur APMC",
    puneApmc: "Pune APMC",
    aurangabad: "Aurangabad",
    enterCredentials: "Enter your credentials to continue",
    email: "Email address",
    password: "Password",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    registerHere: "Register here",
    secured: "Secured",
    dataSource: "Data sourced from Agmarknet & Open-Meteo",
    createAccountCta: "Create free account",
    createAccountBtn: "Create account",
    registerSubtitle: "Join farmers using data-driven decisions",
    name: "Full name",
    phone: "Phone number (optional)",
    confirmPassword: "Confirm password",
    creatingAccount: "Creating account...",
    hasAccount: "Already have an account?",
    loginHere: "Login here",
    dayWeatherForecast: "7-Day weather forecast for",
    loading: "Loading...",
    joinThousands: "Join thousands of farmers earning more.",
    getStartedMinute: "Get started in under a minute",
    role: "Role",
    farmer: "Farmer",
    trader: "Trader",
    admin: "Admin",
    createPassword: "Create a password",
  },
  
  hi: {
    signIn: "साइन इन",
    getStarted: "शुरू करें",
    aiPowered: "AI-संचालित कृषि बुद्धिमत्ता",
    growSmarter: "बेहतर उगाएं।",
    sellBetter: "बेहतर बेचें।",
    earnMore: "अधिक कमाएं।",
    heroSubtitle: "एग्रीरक्षक मौसम पूर्वानुमान, रीयल-टाइम मंडी भाव और मशीन लर्निंग को जोड़ता है।",
    startFree: "मुफ्त शुरू करें",
    farmerLogin: "किसान लॉगिन",
    ticker: ["मौसम पूर्वानुमान", "मंडी भाव", "ML फसल", "परिवहन", "AI अंतर्दृष्टि", "अलर्ट", "तुलना", "रिपोर्ट"],
    recommendationsServed: "सिफारिशें",
    mandiPriceRecords: "भाव रिकॉर्ड",
    cropsSupported: "फसलें",
    farmersOnboarded: "किसान",
    coreTechnology: "मुख्य तकनीक",
    everythingFarming: "स्मार्ट खेती के लिए सब कुछ",
    featuresSubtitle: "चार स्तंभ एक साथ काम करते हैं।",
    weatherIntelligence: "मौसम बुद्धिमत्ता",
    weatherDesc: "रियल-टाइम विश्लेषण खराब होने का जोखिम पहचानता है।",
    mandiPrediction: "भाव पूर्वानुमान",
    mandiDesc: "ML मॉडल 7 दिन पहले भाव बताते हैं।",
    transportCost: "परिवहन लागत",
    transportDesc: "ईंधन, दूरी और लॉजिस्टिक्स का हिसाब।",
    aiDecisions: "AI निर्णय",
    aiDesc: "हर सिफारिश के साथ स्पष्टीकरण।",
    simpleProcess: "सरल प्रक्रिया",
    threeSteps: "लाभ के तीन चरण",
    howSubtitle: "साइन-अप से सिफारिश तक।",
    connectFarm: "अपनी खेती से जुड़ें",
    connectFarmDesc: "अपना स्थान और फसलें दर्ज करें।",
    aiRec: "सिफारिशें प्राप्त करें",
    aiRecDesc: "मॉडल मौसम और भाव का विश्लेषण करते हैं।",
    sellRight: "सही भाव में बेचें",
    sellRightDesc: "अपना इष्टतम समय चुनें और लाभ बढ़ाएं।",
    joinBeta: "बीटा में शामिल हों",
    ctaTitle: "हर फसल से अधिक कमाने के लिए तैयार?",
    ctaSubtitle: "डेटा-संचालित निर्णयों के लिए शामिल हों।",
    helpFeedback: "सहायता और प्रतिक्रिया",
    shareThoughts: "अपने विचार साझा करें",
    feedbackSubtitle: "सर्वश्रेष्ठ उपकरण बनाने में मदद करें।",
    yourName: "आपका नाम",
    emailOptional: "ईमेल (वैकल्पिक)",
    selectType: "प्रकार चुनें",
    featureSuggestion: "फीचर सुझाव",
    bugReport: "बग रिपोर्ट",
    missingMandi: "मंडी/फसल नहीं मिली",
    generalFeedback: "सामान्य प्रतिक्रिया",
    tellUs: "हमें बताएं...",
    sendFeedback: "प्रतिक्रिया भेजें",
    thankYouFeedback: "धन्यवाद! प्रतिक्रिया मिल गई।",
    govtPortals: "सरकारी पोर्टल",
    downloadApp: "ऐप डाउनलोड करें",
    getPlayStore: "गूगल प्ले पर प्राप्त करें",
    getAppStore: "ऐप स्टोर से डाउनलोड करें",
    product: "उत्पाद",
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    supportedCrops: "समर्थित फसलें",
    pricing: "मूल्य निर्धारण",
    changelog: "चेंजलॉग",
    resources: "संसाधन",
    documentation: "दस्तावेज़ीकरण",
    apiAccess: "API एक्सेस",
    blog: "ब्लॉग",
    faqs: "FAQ",
    contactSupport: "संपर्क सहायता",
    dashboard: "डैशबोर्ड",
    getRecommendation: "सिफारिश प्राप्त करें",
    livePrices: "लाइव भाव",
    weather: "मौसम",
    simulator: "सिम्युलेटर",
    history: "इतिहास",
    farmerPortal: "किसान पोर्टल",
    quickStats: "त्वरित आंकड़े",
    recommendations: "सिफारिशें",
    activeCrop: "सक्रिय फसल",
    region: "क्षेत्र",
    notSet: "सेट नहीं",
    signOut: "लॉग आउट",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    farmOverview: "आपका खेती अवलोकन।",
    cropsAvailable: "उपलब्ध फसलें",
    latestEstProfit: "अनुमानित लाभ",
    spoilageRisk: "खराब होने का जोखिम",
    getAiRec: "AI सिफारिश प्राप्त करें",
    recSubtitle: "फसल, क्षेत्र और मात्रा चुनें।",
    crop: "फसल",
    regionState: "क्षेत्र (राज्य)",
    quantity: "मात्रा (क्विंटल)",
    analyze: "विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    soilData: "मिट्टी डेटा (वैकल्पिक)",
    soilPh: "मिट्टी pH",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    storageConditions: "भंडारण स्थितियां",
    storageTemp: "तापमान",
    humidity: "आर्द्रता (%)",
    transitTime: "यात्रा समय",
    aiRecommendation: "AI सिफारिश",
    basedOnWeather: "मौसम और भाव के आधार पर",
    harvestWindow: "कटाई का समय",
    bestNetReturn: "सर्वश्रेष्ठ शुद्ध लाभ",
    priceQuintal: "भाव/क्विंटल",
    estNetProfit: "शुद्ध लाभ",
    aiExplanation: "AI स्पष्टीकरण",
    soilSuitability: "मिट्टी की उपयुक्तता",
    selectCrop: "फसल चुनें",
    pleaseSelectCrop: "कृपया फसल चुनें।",
    pleaseEnterRegion: "कृपया क्षेत्र दर्ज करें।",
    failedToGenerate: "सिफारिश बनाने में विफल।",
    noLivePrices: "कोई लाइव भाव उपलब्ध नहीं।",
    enterRegionCrop: "क्षेत्र दर्ज करें और फसल चुनें।",
    noRecommendations: "अभी तक कोई सिफारिश नहीं।",
    pastRecommendations: "पिछली सिफारिशें",
    cropOptimalRanges: "इष्टतम सीमा",
    preservationRecommendations: "संरक्षण टिप्स",
    cost: "लागत",
    effectiveness: "प्रभावशीलता",
    spoilageRiskEstimator: "खराब होने का जोखिम",
    lowRisk: "कम जोखिम",
    moderateRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    // Login/Register
    welcomeBack: "वापसी पर स्वागत है",
    loginSubtitle: "आपकी व्यक्तिगत फसल और बाजार बुद्धिमत्ता का इंतजार है। आज की AI सिफारिशें देखने के लिए लॉग इन करें।",
    feature1: "7-दिन का मौसम फसल विंडो",
    feature2: "लाइव मंडी भाव पूर्वानुमान",
    feature3: "परिवहन लागत अनुकूलन",
    feature4: "स्पष्टीकरण योग्य AI अंतर्दृष्टि",
    todaysMarket: "आज का बाजार",
    wheat: "गेहूं",
    soybean: "सोयाबीन",
    cotton: "कपास",
    nagpurApmc: "नागपुर APMC",
    puneApmc: "पुणे APMC",
    aurangabad: "औरंगाबाद",
    enterCredentials: "जारी रखने के लिए अपने क्रेडेंशियल दर्ज करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    signingIn: "साइन इन हो रहा है...",
    noAccount: "खाता नहीं है?",
    registerHere: "यहां रजिस्टर करें",
    secured: "सुरक्षित",
    dataSource: "डेटा Agmarknet और Open-Meteo से",
    createAccountCta: "मुफ्त खाता बनाएं",
    createAccountBtn: "खाता बनाएं",
    registerSubtitle: "डेटा-संचालित निर्णयों का उपयोग करने वाले किसानों में शामिल हों",
    name: "पूरा नाम",
    phone: "फोन नंबर (वैकल्पिक)",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    creatingAccount: "खाता बनाया जा रहा है...",
    hasAccount: "पहले से खाता है?",
    loginHere: "यहां लॉग इन करें",
    dayWeatherForecast: "के लिए 7-दिन का मौसम पूर्वानुमान",
    loading: "लोड हो रहा है...",
    joinThousands: "हजारों किसानों में शामिल हों जो अधिक कमा रहे हैं।",
    getStartedMinute: "एक मिनट में शुरू करें",
    role: "भूमिका",
    farmer: "किसान",
    trader: "व्यापारी",
    admin: "प्रशासक",
    createPassword: "पासवर्ड बनाएं",
  },
  
  mr: {
    signIn: "साइन इन",
    getStarted: "सुरू करा",
    aiPowered: "AI-चालित शेती बुद्धिमत्ता",
    growSmarter: "चांगली पिके घ्या.",
    sellBetter: "चांगली विका.",
    earnMore: "जास्त कमवा.",
    heroSubtitle: "एग्रीरक्षक हवामान अंदाज, रिअल-टाइम मंडी भाव आणि मशीन लर्निंग जोडते.",
    startFree: "मोफत सुरू करा",
    farmerLogin: "शेतकरी लॉगिन",
    ticker: ["हवामान अंदाज", "मंडी भाव", "ML पिक", "वाहतूक", "AI अंतर्दृष्टी", "अलर्ट", "तुलना", "रिपोर्ट"],
    recommendationsServed: "शिफारसी",
    mandiPriceRecords: "भाव नोंदी",
    cropsSupported: "पिके",
    farmersOnboarded: "शेतकरी",
    coreTechnology: "मुख्य तंत्रज्ञान",
    everythingFarming: "स्मार्ट शेतीसाठी सर्व काही",
    featuresSubtitle: "चार स्तंभ एकत्र काम करतात.",
    weatherIntelligence: "हवामान बुद्धिमत्ता",
    weatherDesc: "रिअल-टाइम विश्लेषण खराब होण्याचा धोका ओळखतो.",
    mandiPrediction: "भाव अंदाज",
    mandiDesc: "ML मॉडेल 7 दिवस आधी भाव सांगतात.",
    transportCost: "वाहतूक खर्च",
    transportDesc: "इंधन, अंतर आणि लॉजिस्टिक्सचा हिशोब घ्या.",
    aiDecisions: "AI निर्णय",
    aiDesc: "प्रत्येक शिफारसीबरोबर स्पष्टीकरण येतं.",
    simpleProcess: "सोपी प्रक्रिया",
    threeSteps: "नफ्याची तीन पायऱ्या",
    howSubtitle: "साइन-अप ते शिफारसीपर्यंत.",
    connectFarm: "शेताशी जोडा",
    connectFarmDesc: "तुमचं स्थान आणि पिके प्रविष्ट करा.",
    aiRec: "शिफारशी घ्या",
    aiRecDesc: "मॉडेल हवामान आणि भाव विश्लेषण करतात.",
    sellRight: "योग्य भावात विका",
    sellRightDesc: "योग्य वेळ निवडा आणि नफा वाढवा.",
    joinBeta: "बीटामध्ये सामील व्हा",
    ctaTitle: "प्रत्येक पिकातून जास्त कमायला तयार?",
    ctaSubtitle: "डेटा-आधारित निर्णयांसाठी सामील व्हा.",
    helpFeedback: "मदत आणि अभिप्राय",
    shareThoughts: "तुमचे विचार सांगा",
    feedbackSubtitle: "सर्वोत्तम साधन बनवण्यास मदत करा.",
    yourName: "तुमचं नाव",
    emailOptional: "ईमेल (ऐच्छिक)",
    selectType: "प्रकार निवडा",
    featureSuggestion: "वैशिष्ट्य सूचना",
    bugReport: "बग रिपोर्ट",
    missingMandi: "मंडी/पिक आढळली नाही",
    generalFeedback: "सामान्य अभिप्राय",
    tellUs: "आम्हाला सांगा...",
    sendFeedback: "अभिप्राय पाठवा",
    thankYouFeedback: "धन्यवाद! अभिप्राय मिळाला.",
    govtPortals: "सरकारी पोर्टल",
    downloadApp: "अॅप डाउनलोड करा",
    getPlayStore: "गूगल प्ले वर घ्या",
    getAppStore: "अॅप स्टोरवरून डाउनलोड करा",
    product: "उत्पादन",
    features: "वैशिष्ट्ये",
    howItWorks: "हे कसे काम करते",
    supportedCrops: "समर्थित पिके",
    pricing: "किंमत",
    changelog: "बदल",
    resources: "संसाधने",
    documentation: "दस्तावेज़",
    apiAccess: "API प्रवेश",
    blog: "ब्लॉग",
    faqs: "FAQ",
    contactSupport: "संपर्क समर्थन",
    dashboard: "डैशबोर्ड",
    getRecommendation: "शिफारस घ्या",
    livePrices: "लाइव भाव",
    weather: "हवामान",
    simulator: "सिम्युलेटर",
    history: "इतिहास",
    farmerPortal: "शेतकरी पोर्टल",
    quickStats: "त्वरीत आकडे",
    recommendations: "शिफारसी",
    activeCrop: "सक्रिय पिक",
    region: "प्रदेश",
    notSet: "सेट नाही",
    signOut: "लॉग आउट",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दुपार",
    goodEvening: "शुभ संध्याकाळ",
    farmOverview: "तुमचा शेती अवलोकन.",
    cropsAvailable: "उपलब्ध पिके",
    latestEstProfit: "अंदाजे नफा",
    spoilageRisk: "खराब होण्याचा धोका",
    getAiRec: "AI शिफारस घ्या",
    recSubtitle: "पिक, प्रदेश आणि प्रमाण निवडा.",
    crop: "पिक",
    regionState: "प्रदेश (राज्य)",
    quantity: "प्रमाण (क्विंटल)",
    analyze: "विश्लेषण करा",
    analyzing: "विश्लेषण होत आहे...",
    soilData: "माती डेटा (ऐच्छिक)",
    soilPh: "माती pH",
    nitrogen: "नायट्रोजन (N)",
    phosphorus: "फॉस्फरस (P)",
    potassium: "पोटॅशियम (K)",
    storageConditions: "साठवणूक स्थिती",
    storageTemp: "तापमान",
    humidity: "आर्द्रता (%)",
    transitTime: "प्रवास वेळ",
    aiRecommendation: "AI शिफारस",
    basedOnWeather: "हवामान आणि भावावर आधारित",
    harvestWindow: "कापणीची वेळ",
    bestNetReturn: "सर्वोत्तम शुद्ध परतावा",
    priceQuintal: "भाव/क्विंटल",
    estNetProfit: "शुद्ध नफा",
    aiExplanation: "AI स्पष्टीकरण",
    soilSuitability: "माती योग्यता",
    selectCrop: "पिक निवडा",
    pleaseSelectCrop: "कृपया पिक निवडा.",
    pleaseEnterRegion: "कृपया प्रदेश प्रविष्ट करा.",
    failedToGenerate: "शिफारस तयार करण्यात अयशस्वी.",
    noLivePrices: "कोणतेही लाइव भाव उपलब्ध नाहीत.",
    enterRegionCrop: "प्रदेश प्रविष्ट करा आणि पिक निवडा.",
    noRecommendations: "अजून शिफारसी नाहीत.",
    pastRecommendations: "मागील शिफारसी",
    cropOptimalRanges: "इष्टतम श्रेणी",
    preservationRecommendations: "संरक्षण टिप्स",
    cost: "खर्च",
    effectiveness: "प्रभाव",
    spoilageRiskEstimator: "खराब होण्याचा धोका",
    lowRisk: "कमी धोका",
    moderateRisk: "मध्यम धोका",
    highRisk: "जास्त धोका",
    // Login/Register
    welcomeBack: "परत येताना स्वागत आहे",
    loginSubtitle: "तुमची वैयक्तिक आणि बाजार बुद्धिमत्ता वाट पाहत आहे. आजची AI शिफारशी पाहण्यासाठी लॉग इन करा.",
    feature1: "7-दिवस हवामान पिक विंडो",
    feature2: "लाइव मंडी भाव अंदाज",
    feature3: "वाहतूक खर्च ऑप्टिमायझेशन",
    feature4: "स्पष्टीकरण योग्य AI अंतर्दृष्टी",
    todaysMarket: "आजचा बाजार",
    wheat: "गहू",
    soybean: "सोयाबीन",
    cotton: "कापूस",
    nagpurApmc: "नागपूर APMC",
    puneApmc: "पुणे APMC",
    aurangabad: "औरंगाबाद",
    enterCredentials: "पुढे जाण्यासाठी तुमची वैधता प्रविष्ट करा",
    email: "ईमेल पत्ता",
    password: "पासवर्ड",
    signingIn: "साइन इन होत आहे...",
    noAccount: "खाते नाही?",
    registerHere: "येथे नोंदणी करा",
    secured: "सुरक्षित",
    dataSource: "डेटा Agmarknet आणि Open-Meteo वरून",
    createAccountCta: "मोफत खातं तयार करा",
    createAccountBtn: "खाते तयार करा",
    registerSubtitle: "डेटा-आधारित निर्णय वापरणाऱ्या शेतकर्यांमध्ये सामील व्हा",
    name: "पूर्ण नाव",
    phone: "फोन नंबर (ऐच्छिक)",
    confirmPassword: "पासवर्डाची पुष्टी करा",
    creatingAccount: "खाते तयार होत आहे...",
    hasAccount: "आधीपासून खाते आहे?",
    loginHere: "येथे लॉग इन करा",
    dayWeatherForecast: "साठी 7-दिवस हवामान अंदाज",
    loading: "लोड होत आहे...",
    joinThousands: "अधिक कमाणाऱ्या शेतकर्यांमध्ये सामील व्हा.",
    getStartedMinute: "एक मिनिटात सुरू करा",
    role: "भूमिका",
    farmer: "शेतकरी",
    trader: "व्यापारी",
    admin: "प्रशासक",
    createPassword: "पासवर्ड तयार करा",
  },
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("ag_language") || "en";
    }
    return "en";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("ag_language", language);
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
